
---
Name: Tsuru
Modules:
 # - modules/atlys.yaml                # Atlys custom world map system
 # - modules/buffs.yaml                # 'Cause the game is too easy
  - modules/cheats.yaml               # Cheat menu
  - modules/collisionconditions.yaml  # Fixes collision conditions for some actors
  - modules/customactors.yaml         # Custom sprites/actors
  - modules/cutscenetask.yaml         # Custom cutscene video player
  - modules/deathfoo.yaml             # Toxic cloud foo patch
  - modules/debug.yaml                # Debugging features
# - modules/experiments.yaml          # Experimental things #! (WARNING: Do not use in releases)
  - modules/framebuffer.yaml          # Clears the framebuffer before rendering
  - modules/initializer.yaml          # Initializer
  - modules/layout.yaml               # Custom layouts
  - modules/misc.yaml                 # Miscellaneous items
  - modules/powerup.yaml              # Custom powerups
  - modules/profile.yaml              # Extra profile and sprite slots
  - modules/resloader.yaml            # Resource loader
  - modules/sarcloader.yaml           # Allow loading uncompressed .sarc levels
  - modules/savemgr.yaml              # Manages the custom savedata files
  - modules/sead.yaml                 # Patches for the sead library
# - modules/sizemodifier.yaml         # Scale actors as you wish using nybble #! Depends on SetPhysicsMgrOwner from misc.yaml which crashes some levels
  - modules/snowparticles.yaml        # Allows changing snow particle colors from spritedata
  - modules/sound.yaml                # Patches that affect sound
  - modules/titlescreen.yaml          # Title screen patches
  - modules/waves.yaml                # Wavy liquids
  - modules/yoshicolors.yaml          # Extra colors for Yoshi
