
---
Name: NSMBU Haxx
Modules:
# - aa.yaml               # Disables FXAA in-game
  - activecollider.yaml   # 
  - areatask.yaml         # Area modifiers
  - constructors.yaml     # Constructor patches
  - customactors.yaml     # Custom sprites/actors
  - dynamiclibs.yaml      # Dynamic libraries
  - nohurryup.yaml        # Disables rush at 100 secs
  - sead.yaml             # 
  - sound.yaml            # Sound effect and music mods
