
---
Name: SuperHacks
Modules:
  - hooks/cheats.yaml               # Cheat menu
  - hooks/misc.yaml                 # Miscellaneous items
  - hooks/collisionconditions.yaml  # Fixes collision conditions for some actors
  - hooks/customactors.yaml         # Custom sprites/actors
  - hooks/cutscenetask.yaml         # Custom cutscene video player
  - hooks/debug.yaml                # Debugging features
  - hooks/initializer.yaml          # Initializer
  - hooks/profile.yaml              # Extra profile and sprite slots
  - hooks/sarcloader.yaml           # Allow loading uncompressed .sarc levels
  - hooks/sead.yaml                 # Patches for the sead library
  - hooks/shsavemgr.yaml            # Manages the custom savedata file
  - hooks/sizemodifier.yaml         # Scale actors as you wish using nybble 
  - hooks/snowparticles.yaml        # Allows changing snow particle colors from spritedata
  - hooks/sound.yaml                # Patches that affect sound
  - hooks/titlescreen.yaml          # Title screen patches
  - hooks/yoshicolors.yaml          # Extra colors for Yoshi
