
---
Name: SuperHacks
Modules:
# - antialiasing.yaml     # Disables FXAA in-game
  - areatask.yaml         # Area modifiers
  - customsprites.yaml    # Custom sprites/actors
  - debug.yaml            # Debug tools
  - dynamiclibs.yaml      # Dynamic libraries
  - fixes.yaml            # Miscellaneous bugfixes
  - hitboxcollider.yaml   # HitboxCollider patches
  - initializer.yaml      # Initialize static variables and load RPLs
  - misc.yaml             # Miscellaneous patches
  - sarcloader.yaml       # Loads levels as .sarc if .szs isn't found
  - sead.yaml             # Standard library patches
  - sizemodifier.yaml     # Sprite size modifier
  - snowparticles.yaml    # Custom snow particles
  - titlescreen.yaml      # Title screen patches
  - worldmapscripts.yaml  #
  - yoshicolors.yaml      # Patches Yoshis to have all colors
