
---
Name: Tsuru
Modules:
 # - atlys.yaml                # Atlys custom world map system
 # - buffs.yaml                # 'Cause the game is too easy
  - cheats.yaml               # Cheat menu
  - collisionconditions.yaml  # Fixes collision conditions for some actors
  - customactors.yaml         # Custom sprites/actors
  - cutscenetask.yaml         # Custom cutscene video player
  - deathfoo.yaml             # Toxic cloud foo patch
  - debug.yaml                # Debugging features
# - experiments.yaml          # Experimental things #! (WARNING: Do not use in releases)
  - framebuffer.yaml          # Clears the framebuffer before rendering
#  - heap.yaml                 # LETS FREE SOME RAM
  - initializer.yaml          # Initializer
  - misc.yaml                 # Miscellaneous items
#  - powerup.yaml              # Custom powerups
  - profile.yaml              # Extra profile and sprite slots
  - resloader.yaml            # Resource loader
  - sarcloader.yaml           # Allow loading uncompressed .sarc levels
  - savemgr.yaml              # Manages the custom savedata files
  - sead.yaml                 # Patches for the sead library
# - sizemodifier.yaml         # Scale actors as you wish using nybble #! Depends on SetPhysicsMgrOwner from misc.yaml which crashes some levels
  - snowparticles.yaml        # Allows changing snow particle colors from spritedata
  - sound.yaml                # Patches that affect sound
  - titlescreen.yaml          # Title screen patches
  - waves.yaml                # Wavy liquids
  - yoshicolors.yaml          # Extra colors for Yoshi
Defines:
  - Override
  - Cemu
