
---
Name: NSMBU Haxx
Modules:
# - aa.yaml               # Disables FXAA in-game
  - activecollider.yaml   # 
  - areatask.yaml         # Area physics mods
  - asm.yaml              # ASM hacks
  - constructors.yaml     # 
  - custom_actors.yaml    # Custom sprites/actors
  - dynamic_libs.yaml     # Dynamic libraries
  - sead.yaml             # 
  - sound.yaml            # Sound effect and music mods
