
---
Name: Tsuru
ModulesDir: modules
IncludeDir: include
SourceDir: .
RpxDir: +/rpxs
Modules:
  - cheats               # Cheat menu
  - collisionconditions  # Fixes collision conditions for some actors
  - csscripts            # Custom world map scripts
  - customactors         # Custom sprites/actors
  - debug                # Debugging features
#  - experiments          # Experimental things
  - framebuffer          # Framebuffer-related fixes
  - initializer          # Initializer
  - layout               # Custom layouts
  - misc                 # Miscellaneous items
  - patchedactors        # Patches for existing actors
  - powerup              # Custom powerups
  - profile              # Extra profile and sprite slots
  - resloader            # Resource loader
  - sarcloader           # Allow loading uncompressed .sarc levels
  - savemgr              # Manages the custom savedata files
  - sdk                  # SDK library loaders
  - sead                 # Patches for the sead library
  - sound                # Patches that affect sound
  - titlescreen          # Title screen patches
  - yoshicolors          # Extra colors for Yoshi
  - imgui
Defines:
  - cafe
  - NW_RELEASE

Targets:
  US: ~
  EU: ~
  JP: ~
  Template/Tricky:
    Modules:
      - buffs # What if we made the game a bit more tricky...
    Remove/Modules:
      - yoshicolors
    Defines:
      - TARGET_TRICKY
  Tricky_US:
    Extends: Tricky
    AddrMap: US
    BaseRpx: US
  Tricky_EU:
    Extends: Tricky
    AddrMap: EU
    BaseRpx: EU
  Tricky_JP:
    Extends: Tricky
    AddrMap: JP
    BaseRpx: JP
